<?php
/**
 * @file
 * configuration_apachesolr.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function configuration_apachesolr_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "current_search" && $api == "current_search") {
    return array("version" => "1");
  }
  if ($module == "facetapi" && $api == "facetapi_defaults") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
